"""crear tabla implementos

Revision ID: 7a7777420e8a
Revises: ea0b7577dc27
Create Date: 2026-07-02 00:32:13.030160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a7777420e8a'
down_revision: Union[str, Sequence[str], None] = 'ea0b7577dc27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('implementos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('valor_estimado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estados_implemento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_implementos_codigo'), 'implementos', ['codigo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_implementos_codigo'), table_name='implementos')
    op.drop_table('implementos')
    # ### end Alembic commands ###
