"""crear tabla prestamos

Revision ID: 95f38a9c2fca
Revises: cc9d31e504c7
Create Date: 2026-07-04 00:07:21.487326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f38a9c2fca'
down_revision: Union[str, Sequence[str], None] = 'cc9d31e504c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prestamos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('beneficiario_id', sa.Integer(), nullable=False),
    sa.Column('implemento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_entrega_id', sa.Integer(), nullable=False),
    sa.Column('usuario_devolucion_id', sa.Integer(), nullable=True),
    sa.Column('fecha_prestamo', sa.DateTime(), nullable=False),
    sa.Column('fecha_prevista_devolucion', sa.Date(), nullable=True),
    sa.Column('fecha_devolucion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('usuario_responsable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['beneficiarios.id'], ),
    sa.ForeignKeyConstraint(['implemento_id'], ['implementos.id'], ),
    sa.ForeignKeyConstraint(['usuario_devolucion_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_entrega_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_prestamos_numero'), 'prestamos', ['numero'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prestamos_numero'), table_name='prestamos')
    op.drop_table('prestamos')
    # ### end Alembic commands ###
