"""crear tabla beneficiarios correctamente

Revision ID: cc9d31e504c7
Revises: d080838914a0
Create Date: 2026-07-03 17:15:05.889487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc9d31e504c7'
down_revision = "a62dc3b902d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('tipo_documento', sa.String(length=20), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('usuario_responsable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_beneficiarios_activo'), 'beneficiarios', ['activo'], unique=False)
    op.create_index(op.f('ix_beneficiarios_apellido'), 'beneficiarios', ['apellido'], unique=False)
    op.create_index(op.f('ix_beneficiarios_nombre'), 'beneficiarios', ['nombre'], unique=False)
    op.create_index(op.f('ix_beneficiarios_numero_documento'), 'beneficiarios', ['numero_documento'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beneficiarios_numero_documento'), table_name='beneficiarios')
    op.drop_index(op.f('ix_beneficiarios_nombre'), table_name='beneficiarios')
    op.drop_index(op.f('ix_beneficiarios_apellido'), table_name='beneficiarios')
    op.drop_index(op.f('ix_beneficiarios_activo'), table_name='beneficiarios')
    op.drop_table('beneficiarios')
    # ### end Alembic commands ###
